## constants.py

# Motors

RIGHT_MOTOR_DIRECTION    = 29
RIGHT_MOTOR_PWM          = 22

LEFT_MOTOR_DIRECTION     = 30
LEFT_MOTOR_PWM           = 23

# Bump Sensors

BUMP_SENSOR_R_FRONT    = 27
BUMP_SENSOR_R_SIDE     = 25

BUMP_SENSOR_L_FRONT    = 28
BUMP_SENSOR_L_SIDE     = 26

LEFT = 1
RIGHT = 0
